// <auto-generated />
using System;
using M7_Class_37_Work_01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M7_Class_37_Work_01.Migrations.CourseDb
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20201001142450_TradeChanged")]
    partial class TradeChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M7_Class_37_Work_01.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("Duration");

                    b.Property<int>("TradeId");

                    b.HasKey("CourseId");

                    b.HasIndex("TradeId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("M7_Class_37_Work_01.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StudentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("M7_Class_37_Work_01.Models.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("FemaleAllowed");

                    b.Property<bool>("IndustrialAttachment");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("TradeId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("M7_Class_37_Work_01.Models.Course", b =>
                {
                    b.HasOne("M7_Class_37_Work_01.Models.Trade", "Trade")
                        .WithMany("Courses")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M7_Class_37_Work_01.Models.Student", b =>
                {
                    b.HasOne("M7_Class_37_Work_01.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
